namespace FinalFantasy14.Maraudar.MarArm.Head.Level1_10;

public partial class Level1_10 : ContentPage
{
	public Level1_10()
	{
		InitializeComponent();

        Picker picker = new Picker { Title = "Select Marauder's Helmet" };
        picker.Items.Add("Far Eastern Patriarch's Hat");
        picker.Items.Add("Far Eastern Matriarch's Sun Hat");
        picker.Items.Add("Helm of Light");
        picker.Items.Add("Onion Helm");
        picker.Items.Add("Garlond Goggles");
        picker.Items.Add("Moogle Cap");
        picker.Items.Add("Tarnished Face of Undying Twilight");
        picker.Items.Add("Aka Oni Somen");
        picker.Items.Add("Republic Hoplomachus's Headgear");
        picker.Items.Add("Late Allagan Mask of Fending");
        picker.Items.Add("Prestige Crown of Light");
        picker.Items.Add("Prestige High Allagan Circlet of Fending");
        picker.Items.Add("Lone Wolf Crown");
        picker.Items.Add("Pack Wolf Crow");
        picker.Items.Add("Eaglewing Crown");
        picker.Items.Add("Barghest Helm");
        picker.Items.Add("Moddey Dhoo Helm");
        picker.Items.Add("Hempen Coif");
        picker.Items.Add("Hemp Coif of Gathering");
        picker.Items.Add("Leather Calot");
        picker.Items.Add("Company Hat");
        picker.Items.Add("Spotted Fedora");
        picker.Items.Add("Ultima Horns");
        picker.Items.Add("Tamamo Headband");
        picker.Items.Add("Toad Head");
        picker.Items.Add("Gaja Head");
        picker.Items.Add("Expeditioner's Cap");
        picker.Items.Add("Hellhound Helm");
        picker.Items.Add("Grey Hound Helm");
        picker.Items.Add("Koro Kabuto");
        picker.Items.Add("Gunro Kabuto");
        picker.Items.Add("Shdowstalker's Helm");
        picker.Items.Add("Shadowcleaver's Helm");
        picker.Items.Add("Archfiend Helm");
        picker.Items.Add("False Monarchy Mask");
        picker.Items.Add("Catoblepas Horns");
        picker.Items.Add("Bunny Crown");
        picker.Items.Add("Sharlayan Goggles");
        picker.Items.Add("Bunny Chief Crown");
        picker.Items.Add("Cockscomb");
        picker.Items.Add("Coeurl Mask");
        picker.Items.Add("Succubus Horns");
        picker.Items.Add("Swine Head");
        picker.Items.Add("Arch Demon Horns");
        picker.Items.Add("Shaded Visor");
        picker.Items.Add("Vanu Vanu Head");
        picker.Items.Add("Gnath Head");
        picker.Items.Add("Zundu Head");
        picker.Items.Add("Kabuto of the Blue");
        picker.Items.Add("Namazu Mask");
        picker.Items.Add("Replica Behemoth Helm");
        picker.Items.Add("Replica Heavy Behemoth Helm");
        picker.Items.Add("Goblin Cap");
        picker.Items.Add("Fat Chocobo Head");
        picker.Items.Add("Racing Chocobo Mask");
        picker.Items.Add("Expeditioner's Flyers");
        picker.Items.Add("Dragon Monocle");
        picker.Items.Add("Dynasty Crown");
        picker.Items.Add("Ribbon");
        picker.Items.Add("Migratory Plume");
        picker.Items.Add("Monoa Mask");
        picker.Items.Add("Mended Imperial Pot Helm");
        picker.Items.Add("Sable Death Mask");
        picker.Items.Add("Postmoogle Cap");
        picker.Items.Add("Scion Adventurer's Monocle");
        picker.Items.Add("Inspector's Eyeglasses");
        picker.Items.Add("Scion Rogue's Bandana");
        picker.Items.Add("Head Bandage");
        picker.Items.Add("Scion Traveler's Mask");
        picker.Items.Add("Crystarium Helm");
        picker.Items.Add("Appointed Cap");
        picker.Items.Add("Yakaku Kamidome");
        picker.Items.Add("Leafman Head");
        picker.Items.Add("Highland Hood");
        picker.Items.Add("Coronal Straw Hat");
        picker.Items.Add("Spring Straw Hat");
        picker.Items.Add("Cloche");
        picker.Items.Add("Spriggan Cap");
        picker.Items.Add("Crescent Moon Cone");
        picker.Items.Add("Cresecent Moon Nightcap");
        picker.Items.Add("Oval Spectacles");
        picker.Items.Add("Shaded Spectacles");
        picker.Items.Add("Contemporary Pince-nez");
        picker.Items.Add("Rimless Glasses");
        picker.Items.Add("Tick-rimmed Glasses");
        picker.Items.Add("Gryphonskin Eyepatch");
        picker.Items.Add("Imperial Shadow Visor");
        picker.Items.Add("Ministrel's Spectacles");
        picker.Items.Add("Classic Spectacles");
        picker.Items.Add("Imitation Mistbeard Mask");
        picker.Items.Add("The Emperor's New Hat");
        picker.Items.Add("Oval Reading Glasses");
        picker.Items.Add("Coeurl Eyeglasses");
        picker.Items.Add("Thavnairian Turban");
        picker.Items.Add("Thavnairian Headdress");
        picker.Items.Add("Flat Cap");
        picker.Items.Add("Red Beret");
        picker.Items.Add("Green Beret");
        picker.Items.Add("White Beret");
        picker.Items.Add("Elegant Rimless Glasses");
        picker.Items.Add("Reading Glasses");
        picker.Items.Add("High House Cloche");
        picker.Items.Add("Archaeoskin Cloche");
        picker.Items.Add("Wind Silk Wedge Cap");
        picker.Items.Add("New World Headdress");
        picker.Items.Add("Survival Hat");
        picker.Items.Add("Moonfire Hat");
        picker.Items.Add("Boarskin Survival Hat");
        picker.Items.Add("Ramie Hood");
        picker.Items.Add("Cashmere Hood");
        picker.Items.Add("Wool Knit Cap");
        picker.Items.Add("Flannel Knit Cap");
        picker.Items.Add("Taoist's Cap");
        picker.Items.Add("Non La");
        picker.Items.Add("Emperor Hairpin");
        picker.Items.Add("Anemos Hat");
        picker.Items.Add("Anemos Pot Hat");
        picker.Items.Add("Boulevardier's Hat");
        picker.Items.Add("Pagos Bandana");
        picker.Items.Add("Pagos Circlet");
        picker.Items.Add("Quaintrelle's Hat");
        picker.Items.Add("Archaeodemon Horns");
        picker.Items.Add("Rain Hood");
        picker.Items.Add("Replica Sky Pirate's Helm of Fending");
        picker.Items.Add("Replica Sky Pirate's Helm of Maiming");
        picker.Items.Add("Replica Sky Pirate's Mask of Striking");
        picker.Items.Add("Replica Sky Pirate's Beret of Aiming");
        picker.Items.Add("Replica Sky Pirate's Mask of Scouting");
        picker.Items.Add("Replica Sky Pirate's Cap of Healing");
        picker.Items.Add("Replica Sky Pirate's Cap of Casting");
        picker.Items.Add("Replica Sky Rat Mask of Fending");
        picker.Items.Add("Replica Sky Rat Mask of Maiming");
        picker.Items.Add("Replica Sky Rat Mask of Striking");
        picker.Items.Add("Replica Sky Rat Mask of Aiming");
        picker.Items.Add("Replica Sky Rat Mask of Scouting");
        picker.Items.Add("Replica Sky Rat Mask of Healing");
        picker.Items.Add("Replica Sky Rat Mask of Casting");
        picker.Items.Add("Kupo Crown");
        picker.Items.Add("Kupo Knit Cap");
        picker.Items.Add("Hraesvelgr Hat");
        picker.Items.Add("Skyworker's Helmet");
        picker.Items.Add("Calfskin Rider's Cap");
        picker.Items.Add("Frontier Hat");
        picker.Items.Add("Frontier Ribbon");
        picker.Items.Add("Peacelover's Hat");
        picker.Items.Add("Excite-I-Mask");
        picker.Items.Add("Sharlayan Diadema");
        picker.Items.Add("Thavnairian Ribbon");
        picker.Items.Add("Red Ribbon");
        picker.Items.Add("Varsity Flat Cap");
        picker.Items.Add("Isle Explorer's Hat");
        picker.Items.Add("Noir Hat");
        picker.Items.Add("Lawless Enforcer's Hat");
        picker.Items.Add("Isle Shepherd's Headdress");
        picker.Items.Add("Isle Vacationer's Visor");
        picker.Items.Add("Salon Server's Hat");
        picker.Items.Add("Plain Pajama Eye Mask");
        picker.Items.Add("Cactuar Pajama Eye Mask");
        picker.Items.Add("Chocobo Pajama Eye Mask");
        picker.Items.Add("Baronial Hat");
        picker.Items.Add("Island Resort Straw Hat");
        picker.Items.Add("Dried Red Oldrose");
        picker.Items.Add("Dried Blue Oldrose");
        picker.Items.Add("Dried Yellow Oldrose");
        picker.Items.Add("Dried Green Oldrose");
        picker.Items.Add("Dried Orange Oldrose");
        picker.Items.Add("Dried Purple Oldrose");
        picker.Items.Add("Dried White Oldrose");
        picker.Items.Add("Dried Black Oldrose");
        picker.Items.Add("Oldrose Corsage");
        picker.Items.Add("Red Viola Corsage");
        picker.Items.Add("Blue Viola Corsage");
        picker.Items.Add("Yellow Viola Corsage");
        picker.Items.Add("Green Viola Corsage");
        picker.Items.Add("Orange Viola Corsage");
        picker.Items.Add("Purple Viola Corsage");
        picker.Items.Add("White Viola Corsage");
        picker.Items.Add("Black Viola Corsage");
        picker.Items.Add("Rainbow Viola Corsage");
        picker.Items.Add("Red Cherry Blossom Corsage");
        picker.Items.Add("Blue Cherry Blossom Corsage");
        picker.Items.Add("Yellow Cherry Blossom Corsage");
        picker.Items.Add("Green Cherry Blossom Corsage");
        picker.Items.Add("Orange Cherry Blossom Corsage");
        picker.Items.Add("Purple Cherry Blossom Corsage");
        picker.Items.Add("White Cherry Blossom Corsage");
        picker.Items.Add("Black Cherry Blossom Corsage");
        picker.Items.Add("Pink Cherry Blossom Corsage");
        picker.Items.Add("Red Daisy Corsage");
        picker.Items.Add("Blue Daisy Corsage");
        picker.Items.Add("Yellow Daisy Corsage");
        picker.Items.Add("Green Daisy Corsage");
        picker.Items.Add("Orange Daisy Corsage");
        picker.Items.Add("Purple Daisy Corsage");
        picker.Items.Add("White Daisy Corsage");
        picker.Items.Add("Black Daisy Corsage");
        picker.Items.Add("Rainbow Daisy Corsage");
        picker.Items.Add("Red Brightlily Corsage");
        picker.Items.Add("Blue Brightlily Corsage");
        picker.Items.Add("Yellow Brightlily Corsage");
        picker.Items.Add("Green Brightlily Corsage");
        picker.Items.Add("Orange Brightlily Corsage");
        picker.Items.Add("Purple Brightlily Corsage");
        picker.Items.Add("White Brightlily Corsage");
        picker.Items.Add("Black Brightlily Corsage");
        picker.Items.Add("Rainbow Brightlily Corsage");
        picker.Items.Add("Red Dahlia Corsage");
        picker.Items.Add("Blue Dahlia Corsage");
        picker.Items.Add("Yellow Dahlia Corsage");
        picker.Items.Add("Green Dahlia Corsage");
        picker.Items.Add("Orange Dahlia Corsage");
        picker.Items.Add("Purple Dahlia Corsage");
        picker.Items.Add("White Dahlia Corsage");
        picker.Items.Add("Black Dahlia Corsage");
        picker.Items.Add("Rainbow Dahlia Corsage");
        picker.Items.Add("Red Arum Corsage");
        picker.Items.Add("Blue Arum Corsage");
        picker.Items.Add("Yellow Arum Corsage");
        picker.Items.Add("Green Arum Corsage");
        picker.Items.Add("Orange Arum Corsage");
        picker.Items.Add("Purple Arum Corsage");
        picker.Items.Add("White Arum Corsage");
        picker.Items.Add("Black Arum Corsage");
        picker.Items.Add("Rainbow Arum Corsage");
        picker.Items.Add("Red Lily of the Valley Corsage");
        picker.Items.Add("Blue Lily of the Valley Corsage");
        picker.Items.Add("Yellow Lily of the Valley Corsage");
        picker.Items.Add("Green Lily of the Valley Corsage");
        picker.Items.Add("Orange Lily of the Valley Corsage");
        picker.Items.Add("Purple Lily of the Valley Corsage");
        picker.Items.Add("White Lily of the Valley Corsage");
        picker.Items.Add("Black Lily of the Valley Corsage");
        picker.Items.Add("Rainbow Lily of the Valley Corsage");
        picker.Items.Add("Red Hydrangea Corsage");
        picker.Items.Add("Blue Hydrangea Corsage");
        picker.Items.Add("Yellow Hydrangea Corsage");
        picker.Items.Add("Green Hydrangea Corsage");
        picker.Items.Add("Orange Hydrangea Corsage");
        picker.Items.Add("Purple Hydrangea Corsage");
        picker.Items.Add("White Hydrangea Corsage");
        picker.Items.Add("Black Hydrangea Corsage");
        picker.Items.Add("Rainbow Hydrangea Corsage");
        picker.Items.Add("Red Campanula Corsage");
        picker.Items.Add("Blue Campanula Corsage");
        picker.Items.Add("Yellow Campanula Corsage");
        picker.Items.Add("Green Campanula Corsage");
        picker.Items.Add("Orange Campanula Corsage");
        picker.Items.Add("Purple Campanula Corsage");
        picker.Items.Add("White Campanula Corsage");
        picker.Items.Add("Black Campanula Corsage");
        picker.Items.Add("Rainbow Campanula Corsage");
        picker.Items.Add("Red Hyacinth Corsage");
        picker.Items.Add("Blue Hyacinth Corsage");
        picker.Items.Add("Yellow Hyacinth Corsage");
        picker.Items.Add("Green Hyacinth Corsage");
        picker.Items.Add("Orange Hyacinth Corsage");
        picker.Items.Add("Purple Hyacinth Corsage");
        picker.Items.Add("White Hyacinth Corsage");
        picker.Items.Add("Black Hyacinth Corsage");
        picker.Items.Add("Rainbow Hyacinth Corsage");
        picker.Items.Add("Red Cosmos Corsage");
        picker.Items.Add("Blue Cosmos Corsage");
        picker.Items.Add("Yellow Cosmos Corsage");
        picker.Items.Add("Green Cosmos Corsage");
        picker.Items.Add("Orange Cosmos Corsage");
        picker.Items.Add("Purple Cosmos Corsage");
        picker.Items.Add("White Cosmos Corsage");
        picker.Items.Add("Black Cosmos Corsage");
        picker.Items.Add("Rainbow Cosmos Corsage");
        picker.Items.Add("Red Morning Glory Corsage");
        picker.Items.Add("Blue Morning Glory Corsage");
        picker.Items.Add("Yellow Morning Glory Corsage");
        picker.Items.Add("Green Morning Glory Corsage");
        picker.Items.Add("Orange Morning Glory Corsage");
        picker.Items.Add("Purple Morning Glory Corsage");
        picker.Items.Add("White Morning Glory Corsage");
        picker.Items.Add("Black Morning Glory Corsage");
        picker.Items.Add("Rainbow Morning Glory Corsage");
        picker.Items.Add("Red Chrysanthemum Corsage");
        picker.Items.Add("Blue Chrysanthemum Corsage");
        picker.Items.Add("Yellow Chrysanthemum Corsage");
        picker.Items.Add("Green Chrysanthemum Corsage");
        picker.Items.Add("Orange Chrysanthemum Corsage");
        picker.Items.Add("Purple Chrysanthemum Corsage");
        picker.Items.Add("White Chrysanthemum Corsage");
        picker.Items.Add("Black Chrysanthemum Corsage");
        picker.Items.Add("Rainbow Chrysanthemum Corsage");
        picker.Items.Add("Usagi Kabuto");
        picker.Items.Add("Dragon Kabuto");
        picker.Items.Add("Crimson Dragon Kabuto");
        picker.Items.Add("Golden Dragon Kabuto");
        picker.Items.Add("Black Dragon Kabuto");
        picker.Items.Add("Silver Snake Kabuto");
        picker.Items.Add("Uma Kabuto");
        picker.Items.Add("Crimson Uma Kabuto");
        picker.Items.Add("Golden Uma Kabuto");
        picker.Items.Add("Black Uma Kabuto");
        picker.Items.Add("Hitsuji Kabuto");
        picker.Items.Add("Black Hitsuji Kabuto");
        picker.Items.Add("Crimson Hitsuji Kabuto");
        picker.Items.Add("White Hitsuji Kabuto");
        picker.Items.Add("See No Helm");
        picker.Items.Add("Speak No Helm");
        picker.Items.Add("Hear No Helm");
        picker.Items.Add("Red Tori Kabuto");
        picker.Items.Add("Black Tori Kabuto");
        picker.Items.Add("White Inu Kabuto");
        picker.Items.Add("Black Inu Kabuto");
        picker.Items.Add("Inoshishi Kabuto");
        picker.Items.Add("Crimson Inoshishi Kabuto");
        picker.Items.Add("Crimson Nezumi Kabuto");
        picker.Items.Add("Cobalt Nezumi Kabuto");
        picker.Items.Add("Crimson Ushi Kabuto");
        picker.Items.Add("Black Ushi Kabuto");
        picker.Items.Add("Golden Tora Kabuto");
        picker.Items.Add("Silver Tora Kabuto");
        picker.Items.Add("Valentione Hat");
        picker.Items.Add("Black-featherd Flat Hat");
        picker.Items.Add("Red-feathered Flat Hat");
        picker.Items.Add("Valentione Rose Hat");
        picker.Items.Add("Valentione Forget-me-not Hat");
        picker.Items.Add("Valentione Acacia Hat");
        picker.Items.Add("Valentione Rose Ribboned Hat");
        picker.Items.Add("Velntione Forget-me-not Ribboned Hat");
        picker.Items.Add("Valentione Acacia Ribboned Hat");
        picker.Items.Add("Lovely Moogle Cap");
        picker.Items.Add("Valentione Emissary's Hat");
        picker.Items.Add("Valentione Emissary's Dress Hat");
        picker.Items.Add("Songbird Hat");
        picker.Items.Add("Royal Seneschal's Chapeau");
        picker.Items.Add("Flower Crown");
        picker.Items.Add("Seneschal's Monocle");
        picker.Items.Add("Princess's Peach Corsage");
        picker.Items.Add("Little Lady's Crown");
        picker.Items.Add("Rabbit Head");
        picker.Items.Add("Chicken Head");
        picker.Items.Add("Tonberry Head");
        picker.Items.Add("Oschon Roselle Capeline");
        picker.Items.Add("Gold Roselle Capeline");
        picker.Items.Add("Pearl Roselle Capeline");
        picker.Items.Add("Straw Capeline");
        picker.Items.Add("Endless Summer Glasses");
        picker.Items.Add("Moonfire Hachimaki");
        picker.Items.Add("White Painted Moogle Mask");
        picker.Items.Add("Black Painted Moogle Mask");
        picker.Items.Add("Painted Namazu Mask");
        picker.Items.Add("Summer's Flame Hat");
        picker.Items.Add("Summer Sunset Bandana");
        picker.Items.Add("Pumpking Head");
        picker.Items.Add("Unripened Pumpking Head");
        picker.Items.Add("White Pumpkin Head");
        picker.Items.Add("Ripened Pumpkin Head");
        picker.Items.Add("Eerie Hat");
        picker.Items.Add("Witch's Hat");
        picker.Items.Add("Werewolf Head");
        picker.Items.Add("Clown's Hat");
        picker.Items.Add("Wake Doctor's Mask");
        picker.Items.Add("Dream Hat");
        picker.Items.Add("Reindeer Antlers");
        picker.Items.Add("Snowman Head");
        picker.Items.Add("Starlight Sugarloaf Hat");
        picker.Items.Add("False Mustache");
        picker.Items.Add("Reindeer Antler Headband");
        picker.Items.Add("Saint's Beard");
        picker.Items.Add("Saint's Cap");
        picker.Items.Add("Choir Hat");
        picker.Items.Add("Baron Helm");
        picker.Items.Add("Baron Circlet");
        picker.Items.Add("Wild Rose Bandana");
        picker.Items.Add("Amatsu Hachigane");
        picker.Items.Add("Legacy Warrior Coronet");
        picker.Items.Add("King Slime Crown");
        picker.Items.Add("Augmented Rathalos Helm [M]");
        picker.Items.Add("Augmented Rathalos Helm [F]");
        picker.Items.Add("Rathalos Helm [M]");
        picker.Items.Add("Rathalos Helm [F]");
        picker.Items.Add("No.2 Ype B Goggles");
        picker.Items.Add("Sweet Dream Cap");
        picker.Items.Add("Tetsuji Usagi Kabuto");
        picker.Items.Add("Black Tetsuji Usagi Kabuto");
        picker.Items.Add("Silver Tetsuji Usagi Kabuto");
        picker.Items.Add("Veil of Eternal Innocence");
        picker.Items.Add("Veil of Eternal Passion");
        picker.Items.Add("Veil of Eternal Devotion");
        picker.Items.Add("Moogle Head");
        picker.Items.Add("Yellow-pommed Moogle Cap");
        picker.Items.Add("Scion Striker's Visor");
        picker.Items.Add("Scion Thaumaturge's Monocle");
        picker.Items.Add("Head Engineer's Goggles");
        picker.Items.Add("Ironworks Engineer's Goggles");
        picker.Items.Add("Housemaid's Brim");
        picker.Items.Add("Butler's Monocle");
        picker.Items.Add("Far Eastern Noble's Mortarboard");
        picker.Items.Add("Angelic Circlet");
        picker.Items.Add("Demonic Horns");
        picker.Items.Add("Far Eastern Gentleman's Hat");
        picker.Items.Add("Far Eastern Beauty's Hairpin");
        picker.Items.Add("Star of the Nezha Lord");
        picker.Items.Add("Star of the Nezha Lady");
        picker.Items.Add("Loyal Housemaid's Brim");
        picker.Items.Add("Loyal Butler's Monocle");
        picker.Items.Add("Blackbosom Hat");
        picker.Items.Add("Emerald Carbuncle Ears");
        picker.Items.Add("Topaz Carbuncle Ears");
        picker.Items.Add("Faerie Tale Prince's Circlet");
        picker.Items.Add("Faerie Tale Princess's Tiara");
        picker.Items.Add("Cracked Manderville Monocle");
        picker.Items.Add("Mun'gaek Hat");
        picker.Items.Add("Eastern Socialite's Hat");
        picker.Items.Add("Far Eastern Officer's Hat");
        picker.Items.Add("Far Eastern Maiden's Hat");
        picker.Items.Add("Leal Samurai's Kasa");
        picker.Items.Add("Far Eastern Schoolboy's Hat");
        picker.Items.Add("Far Eastern Schoolgirl's Hair Ribbon");
        picker.Items.Add("Scion Hearer's Hood");
        picker.Items.Add("Peacock Hat");
        picker.Items.Add("Eastern Lord Errant's Hat");
        picker.Items.Add("Eastern Lady Errant's Hat");
        picker.Items.Add("Mheg Deaca Circlet");
        picker.Items.Add("Scion Sorceress's Headdress");
        picker.Items.Add("Ruby Carbuncle Ears");
        picker.Items.Add("Bergsteiger's Hat");
        picker.Items.Add("Dirndl's Hat");
        picker.Items.Add("Resshi Hachigane");
        picker.Items.Add("Street Cap");
        picker.Items.Add("Fat Cat Hood");
        picker.Items.Add("Far Northern Headpiece");
        picker.Items.Add("Educand's Cap");
        picker.Items.Add("Scarf of Wondrous Wit");
        picker.Items.Add("Friendship Circlet");
        picker.Items.Add("Inferno Mask");
        picker.Items.Add("Crag Mask");
        picker.Items.Add("Eastern Journey Circlet");
        picker.Items.Add("Cait Sith Ears");
        picker.Items.Add("Exclusive Eastern Journey Circlet");
        picker.Items.Add("Matoya's Hat");
        picker.Items.Add("Leather Eyepatch");
        picker.Items.Add("Hempen Bandana");
        picker.Items.Add("Hempen Hat");
        picker.Items.Add("Bronze Chain Coif");
        picker.Items.Add("Hard Leather Pot Helm");
        picker.Items.Add("Bronze Sallet");
        picker.Items.Add("Straw Hat");
        picker.Items.Add("Amateur's Headgear");
        picker.Items.Add("Amateur's Hempen Coif");
        picker.Items.Add("Pristine Egg Cap");
        picker.Items.Add("Thug's Mug");
    }

    //private async void OnPickerSelectedIndexChanged(object sender, EventArgs e)
    //{
    //    var picker = (Picker)sender;
    //    int selectedIndex = picker.SelectedIndex;

    //    if (selectedIndex == 0)
    //    {
    //        await Navigation.PushAsync(new Warrior.WarArm.Head.Level1_10.FEPatHat());
    //    }
    //    else if (selectedIndex == 1)
    //    {
    //        await Navigation.PushAsync(new Warrior.WarArm.Head.Level1_10.FEMatSunHat());
    //    }
    //    else if (selectedIndex == 2)
    //    {
    //        await Navigation.PushAsync(new Warrior.WarArm.Head.Level1_10.HelmofLight());
    //    }
    //}
}